name: ASP.NET Core CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: [ubuntu-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0'
    
    - name: Build and Test
      run: dotnet build --configuration Release

    - name: Run Application
      run: dotnet watch run

    - name: Install stylecop
      run: dotnet tool install StyleCop.MSBuild --tool-path . --version <1.0.2>

    - name: Start Application
      run: dotnet stylecop
